apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
  namespace: argo-workflows
spec:
  workflowMetadata:
    labels:
      plugin: argo-kedro
  entrypoint: pipeline
  templates:
  - name: kedro
    metadata:
      labels:
        app: argo-kedro
    inputs:
      parameters:
      - name: pipeline
      - name: kedro_nodes
    container:
      image: us-central1-docker.pkg.dev/mtrx-hub-dev-3of/matrix-images/fuse:latest
      command:
      - kedro
      imagePullPolicy: Always
      args:
      - run
      - --pipeline
      - '{{inputs.parameters.pipeline}}'
      - --nodes
      - '{{inputs.parameters.kedro_nodes}}'
      - --env
      - cloud
  - name: pipeline
    dag:
      tasks:
      - name: data-processing-fused
        template: kedro
        arguments:
          parameters:
          - name: pipeline
            value: data_processing
          - name: kedro_nodes
            value: data_processing_fused
