apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
  namespace: test
spec:
  workflowMetadata:
    labels:
      plugin: argo-kedro
  entrypoint: pipeline
  templates:
  - name: kedro
    metadata:
      labels:
        app: argo-kedro
    inputs:
      parameters:
      - name: pipeline
      - name: kedro_nodes
    container:
      image: dummy
      command:
      - kedro
      imagePullPolicy: Always
      args:
      - run
      - --pipeline
      - '{{inputs.parameters.pipeline}}'
      - --nodes
      - '{{inputs.parameters.kedro_nodes}}'
      - --env
      - base
  - name: pipeline
    dag:
      tasks:
      - name: compare-plot-c
        template: kedro
        arguments:
          parameters:
          - name: pipeline
            value: __default__
          - name: kedro_nodes
            value: compare_plot_c
      - name: data-processing-fused
        template: kedro
        arguments:
          parameters:
          - name: pipeline
            value: __default__
          - name: kedro_nodes
            value: data_processing_fused
      - name: compare-plot-a
        template: kedro
        dependencies:
        - data-processing-fused
        arguments:
          parameters:
          - name: pipeline
            value: __default__
          - name: kedro_nodes
            value: compare_plot_a
      - name: compare-plot-b
        template: kedro
        dependencies:
        - data-processing-fused
        arguments:
          parameters:
          - name: pipeline
            value: __default__
          - name: kedro_nodes
            value: compare_plot_b
      - name: data-science-fused
        template: kedro
        dependencies:
        - data-processing-fused
        arguments:
          parameters:
          - name: pipeline
            value: __default__
          - name: kedro_nodes
            value: data_science_fused
